//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Practike.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academics
    {
        public int Id_Academic { get; set; }
        public string FIO { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Speciality { get; set; }
        public int Year_Awarding_Title { get; set; }
    }
}
