//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Practike.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public int Id_Country { get; set; }
        public string Name { get; set; }
        public string Capital { get; set; }
        public int Square { get; set; }
        public int Population { get; set; }
        public string Continenti { get; set; }
    }
}
