//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Practike.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Kod_Exam { get; set; }
        public System.DateTime Date { get; set; }
        public int Kod_Disciplina { get; set; }
        public int Reg_Number { get; set; }
        public int Tab_Number { get; set; }
        public string Lecture_Hall { get; set; }
        public int estimation { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
