//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Practike.DBConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ed_Practice_Fay320Entities1 : DbContext
    {
        public Ed_Practice_Fay320Entities1()
            : base("name=Ed_Practice_Fay320Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academics> Academics { get; set; }
        public virtual DbSet<Animal_Fayzullina> Animal_Fayzullina { get; set; }
        public virtual DbSet<Control_Fayzullina> Control_Fayzullina { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Countries_Fayzullina> Countries_Fayzullina { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Disciplina> Disciplina { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Engineer> Engineer { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Flowers_Fayzullina> Flowers_Fayzullina { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Zav_Cafedri> Zav_Cafedri { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
        public virtual DbSet<Licei> Licei { get; set; }
    }
}
