//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Practike.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        public string Id_Zayavka { get; set; }
        public string Number_Speciality { get; set; }
        public Nullable<int> Kod_Discipline { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
